services:

  worker:
    image: k2m30/ruby_worker:1.0
    depends_on:
      - db
    env_file: .env
    networks:
      - default

  tests:
    image: k2m30/tests:1.0
    depends_on:
      - db
      - client
    env_file: .env
    networks:
      - default

  server:
    image: k2m30/js_server:1.0
    depends_on:
      - db
    env_file: .env
    expose:
      - 8080
    networks:
      - default

  client:
    image: k2m30/nginx_client:1.0
    depends_on:
      - server
      - db
    ports:
      - 80:80
      - 443:443
    volumes:
      - certbot-etc:/etc/letsencrypt
      - certbot-challenges:/etc/letsencrypt/challenges
    networks:
      default:

  db:
    image: mysql:8.0.23
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    restart: always
    env_file: .env
    expose:
      - 3306
    volumes:
      - ./mysql/data:/var/lib/mysql
    networks:
      - default

  certbot:
    image: certbot/certbot
    container_name: certbot
#    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    volumes:
      - certbot-etc:/etc/letsencrypt
      - certbot-challenges:/etc/letsencrypt/challenges
    depends_on:
      - client
    command: certonly --webroot --webroot-path=/etc/letsencrypt/challenges --rsa-key-size 4096 --email 1m@tut.by --agree-tos --no-eff-email -d docker.spiski.live

volumes:
  certbot-etc:
    driver: local
    driver_opts:
      type: none
      device: ./letsencrypt
      o: bind

  certbot-challenges:
    driver: local
    driver_opts:
      type: none
      device: ./letsencrypt/challenges
      o: bind

networks:
  default:
    driver: bridge
    attachable: true
